steps:

- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: './frontend'

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: './frontend'

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'frontend/build', 'gs://tfg-bas-testing/tfg-bas/frontend/build']



