runtime: java17
instance_class: F2

handlers:
  # Maneja las solicitudes a los archivos estáticos generados por React
  - url: /(.*\.(js|css|png|jpg|gif|ico|html|json|svg))$
    static_files: build/\1
    upload: build/(.*\.(js|css|png|jpg|gif|ico|html|json|svg))$

  # Maneja las solicitudes a las API REST de Spring Boot
  - url: /api/v1/.*
    script: this field is required, but ignored for static files

